### Ping
GET http://localhost:3003/ping

### Signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name": "Vinicius",
  "email": "vinicius@gmail.com",
  "password": "123456",
  "role": "ADMIN"
}

### Login

POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "vinicius@gmail.com",
  "password": "123456"
}

### Post Show
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg2MDk2NTc4LWNhNGYtNDRhYy1iMTZiLTI1M2Y3YzNlYjg2ZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NDU2NTM4NiwiZXhwIjoxNjY0NjUxNzg2fQ.XWZgg2Vn5Q8IhP5TkmJ3KmIvS7v8mSZ4RsECtRUQsas

POST http://localhost:3003/show
Content-Type: application/json
Authorization: {{token}}

{
  "band": "Leigh-Anne",
  "startsAt": "31/12/2022"
}

### 
